### PR TITLE
Start slow

### PR DESCRIPTION
**Pull request by mixmix**
experiment in speeding up tests

### CODE REVIEW

**Comment by mixmix** [comment]
Sigh, not sure why this doesn't work

**Comment by staltz** [comment]
I'm not sure it's worth spending time on this, but a quick inspection shows that most of the time is spent idle. There are a bunch of 200ms or 1000ms waits in between. This is the profiler for the add-member test file:

Screenshot from 2023-02-17 12-00-15@2x

**Comment by mixmix** [comment]
Can you show me how to generate profiler things like that? Are you running an inspector thing to chrome?
There's a bunch of waits between the feeds being added in replication. like 200ms between each... presumably some race condition in `ssb-meta-feeds` ...
But I also notice that startup is really slow with meta feeds (3 seconds!). This is likely the first time cost only, not sure.

**Comment by staltz** [comment]
`node --inspect-brk test/the-file.js` and then open Chrome, go to the address `chrome://inspect` and click the link that it detected on that page.

Notice that from https://github.com/ssbc/ssb-meta-feeds/pull/121#issuecomment-1434428800 I think these 200ms waits are from using lodash.debounce in ssb-db2 and async-append-only-log. Some of which are customizable with a config, others aren't.

Also, beware of yak shaving. I think your time could be more useful elsewhere.

**Pull request closed without merging**
