### PR TITLE
Pin meta feeds to 0.38.1

### PR DESCRIPTION
**Pull request by Powersource**
Tests are broken and i think this fixes them

### CODE REVIEW

**Comment by staltz** [comment]
Do you know why a newer ssb-meta-feeds breaks ssb-tribes2?

**Comment by Powersource** [comment]
tried doing some digging here but didn't come up with much https://github.com/ssbc/ssb-tribes2/pull/44#pullrequestreview-1237351702

**Comment by staltz** [comment]
Seems like it needs more digging, we need these libraries (ssb-db2, ssb-meta-feeds, ssb-tribes2) to be working at their latest versions since we're working on all of them in this project. Otherwise we can't update ssb-meta-feeds in the stack.

**Comment by Powersource** [comment]
is it fine to merge this for now to get tests passing?

**Review by staltz — APPROVED** [review]
Please make a "must" issue in ssb-tribes2 to support ssb-meta-feeds >=0.38.2, I think it's something to be fixed as soon as we can, because there is code already using these libraries (e.g. in arj's ssb-browser-demo)

**Comment by Powersource** [comment]
made issue https://github.com/ssbc/ssb-tribes2/issues/48

**Pull request merged**
